name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2020-12-02
version: '9.1.0'
project: 'drupal'
datestamp: 1606933306
